### ISSUE TITLE
Error while generating new certificate

### ISSUE THREAD

**Issue by Lopuch** [dvoituron/AzureLetsEncrypt#2]
Hello,
I have an error while generating new certificate. This is console output:
`D:\home>md AzureLetsEncrypt

D:\home>
D:\home\AzureLetsEncrypt>dotnet AzureLetsEncrypt.dll
$> Creation of './store' folder
$> openssl genrsa -out ./store/admin-bezsousedu-cz-private.key 2048
   WARNING: can't open config file: C:/OpenSSL/openssl.cnf
   Loading 'screen' into random state - done
   Generating RSA private key, 2048 bit long modulus
   ....................+++
   ...+++
   e is 65537 (0x10001)
   
$> openssl genrsa -out ./store/admin-bezsousedu-cz-account-le.key 4096
   WARNING: can't open config file: C:/OpenSSL/openssl.cnf
   Loading 'screen' into random state - done
   Generating RSA private key, 4096 bit long modulus
   .....................++
   ..............................++
   e is 65537 (0x10001)
   
$> Creation of 'D:/home/site/wwwroot\.well-known\acme-challenge' folder
$> le64 --key ./store/admin-bezsousedu-cz-account-le.key --csr ./store/admin-bezsousedu-cz-signing-le.csr --csr-key ./store/admin-bezsousedu-cz-private.key --crt ./store/admin-bezsousedu-cz.crt --domains "admin.bezsousedu.cz" --generate-missing --path D:/home/site/wwwroot\.well-known\acme-challenge\ --unlink --live
   2019/12/03 15:02:14 [ ZeroSSL Crypt::LE client v0.32 started. ]
   2019/12/03 15:02:14 Loading an account key from ./store/admin-bezsousedu-cz-account-le.key
   2019/12/03 15:02:14 Generating a new CSR for domains admin.bezsousedu.cz
   2019/12/03 15:02:14 New CSR will be based on './store/admin-bezsousedu-cz-private.key' key
   2019/12/03 15:02:14 Saving a new CSR into ./store/admin-bezsousedu-cz-signing-le.csr
   2019/12/03 15:02:15 Registering the account key
   2019/12/03 15:02:15 Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
   
$> Remove the 'D:/home/site/wwwroot\.well-known\acme-challenge' folder
ERROR: GENERATIION FAILED.`

Am I doing something wrong? I followed your youtute tutorial.

Many thanks.

**Comment by dvoituron** [comment]
Arg... Like the [error link ](https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430) said: **Since November 2020 we will no longer allow unauthenticated resource GETs when using ACMEv2**.

I'll updated the integrated tool to use the last version (this week).

Thanks for your feedback

**Comment by dvoituron** [comment]
The version 1.4.0 solved this problem.
