### ISSUE TITLE
Support of Acme V2

### ISSUE THREAD

**Issue by EmmanuelDURIN** [dvoituron/AzureLetsEncrypt#3]
Running AzureLetsEncrypt I got the following message :

2019/12/23 19:34:07 Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.

May be AcmeV2 support would be fine.

Anyway thanks for the job

**Comment by EmmanuelDURIN** [comment]
It seems that it is already fixed in release 1.4.
My error comes from the fact I downloaded release 1.0 for which there is a lin k in readme.md
I try ASAP. But it seems to be the solution

Regards

**Comment by EmmanuelDURIN** [comment]
After updating appsettings.json with my domains and password + setting properties of appsettings.json to "Copy if newer",
I zipped the result of the publish folder and uploaded it to Azure as a triggered webjob, and everything went fine

Thanks Denis

**Comment by dvoituron** [comment]
Indeed, the last version fix this problem :-)
Thanks for your feedback
